### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by cicoph** [consultnn/yii2-mongodb-embedded#1]
Hi, thank you for your ext but I don't understand how to implement it. Can you explain more in the README file? Thank you :)

**Comment by cicoph** [comment]
This is the way to load the Embedded Model in the main collection model

``` php
public function behaviors()
    {
        return [
            'address' => [
                  'class' => EmbedsOneBehavior::className(),
                  'attribute' => '_address',
                  'embedded' => Address::className()
             ],
             'phones' => [
                  'class' => EmbedsManyBehavior::className(),
                  'attribute' => '_phones',
                  'initEmptyScenarios' => ['create', 'update'],
                  'embedded' => Phone::className()
              ],
        ];
    }
```

**Comment by sokrat** [comment]
In commit https://github.com/consultnn/yii2-mongodb-embedded/commit/46b4c7b61282eac8cdb1d4fbcc0108daa51bde17 I renamed EmbeddedClass attribute to "embedded", now vallue support array config for embedded model
