### ISSUE TITLE
Calling unknown method: consultnn\embedded\Storage::formName()

### ISSUE THREAD

**Issue by zerojuls** [consultnn/yii2-mongodb-embedded#10]
Hi I'm having an issue to display a form in view of creation. The way I've done the code is as follows:

My behavior in model document:

```
'country' => [
                'class' => EmbedsManyBehavior::className(),
                'attribute' => '_country',
                // 'initEmptyScenarios' => ['create', 'update'],
                'embedded' => Country::className()
            ],
```

My subdocument model:

```
use Yii;
use consultnn\embedded\EmbeddedDocument;

class Country extends EmbeddedDocument
{
    public $name;
    public $code;

    public function rules()
    {
        return [
            [['name', 'code'], 'safe', 'on'=>'default'],
        ];
    }

}
```

My view form:

```
<?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->label('Location name') ?>
    <?= $form->field($model->country, 'name')->label('Country name') ?>
    <?= $form->field($model->country, 'code')->label('Country code') ?>


    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

<?php ActiveForm::end(); ?>
```

And it shows this error. Any help is appreciated.

![bug-embedded-2](https://cloud.githubusercontent.com/assets/8573420/12516080/8ed6ebda-c0f9-11e5-8764-33db092016c7.png)

![bug-embedded](https://cloud.githubusercontent.com/assets/8573420/12515665/7325db78-c0f7-11e5-9dc2-2cd345d97cc9.png)

**Comment by sokrat** [comment]
Your country attribute contains array of subdocuments, because you attach EmbedsManyBehavior. If it really what you want, then use 'foreach' for render, such as:

```
// Phones
foreach($company->phones as $key => $phone) {
    echo $form->field($phone, 'number');
    echo $form->field($phone, 'type');
}
```

or try https://github.com/consultnn/yii2-multi-embedded-widget
Otherwise, if attribute should contains only one country, attach EmbedsOneBehavior
