### ISSUE TITLE
'required' vaildation doesn't work in the embedded model

### ISSUE THREAD

**Issue by qpi** [consultnn/yii2-mongodb-embedded#13]
If I use the 'required' validation for any filed in the embedded model, it always replies that it can not be empty, whatever I send value or not

**Comment by sokrat** [comment]
May be you try set unsafe attribute?

**Comment by sokrat** [comment]
Attach code example

**Comment by qpi** [comment]
Sorry, but because of this issue https://github.com/consultnn/yii2-mongodb-embedded/issues/12 I had to reverted all my work. I spent several hours to make the multi level embedded model working  :( and because I was not success, I had to find another way to do my taks. Right now I don't have time to create a dummy code to show the problem, maybe in the near future I could send it You
