### ISSUE TITLE
How I can use it with ActiveRecord::find() ?

### ISSUE THREAD

**Issue by retnek** [consultnn/yii2-mongodb-embedded#14]
I can't find the solution how I should filter on an embedded document.

`ActiveRecord:findOne(['field' => $embeddedDocumentInstance]);`

its not working.

**Comment by sokrat** [comment]
try `ActiveRecord:findOne(['field' => $embeddedDocumentInstance->attributes]);`

**Comment by retnek** [comment]
It's working with `$class->attributes`. Thanks!
