### ISSUE TITLE
Нужна проксировать все события из owner в storage модель

### ISSUE THREAD

**Issue by lav45** [consultnn/yii2-mongodb-embedded#5]
https://github.com/consultnn/yii2-mongodb-embedded/blob/master/AbstractEmbeddedBehavior.php#L75-L77

Нужна проксировать все события из owner в storage модель
тогда к storage можно будет подключить практически любой behavior

**Comment by sokrat** [comment]
Добавил(b24dbbd4e411b81458b0c96a5d747c43355ed22f) свойство $events, т.е. его можно переопределить и вызывать метод proxy() на необходимые события
