### ISSUE TITLE
Версии связанных пакетов

### ISSUE THREAD

**Issue by lav45** [consultnn/yii2-mongodb-embedded#7]
https://github.com/consultnn/yii2-mongodb-embedded/blob/master/composer.json#L18-L19
Если ваше приложение обновить через годик когда yii2 будет иметь версию >2.1 есть очень большая вероятность что сайт на котором используется ваш пакет просто перестанет работать.

Версии пакетов нужна указывать хотя бы до minor версий `"yiisoft/yii2": "2.0.*",`

**Comment by sokrat** [comment]
done c5d9c7262946eae038e80617670eb11bf893fa04
