### ISSUE TITLE
Нет необходимости указывать в зависимостях yiisoft/yii2-mongodb

### ISSUE THREAD

**Issue by lav45** [consultnn/yii2-mongodb-embedded#8]
https://github.com/consultnn/yii2-mongodb-embedded/blob/master/composer.json#L19

Ваше приложение без проблем может работать с любой базой данных.
Нет необходимости указывать в зависимостях `yiisoft/yii2-mongodb`

PS Я бы и из названия удалил `mongodb`

**Comment by sokrat** [comment]
Зависимость убрал c5d9c7262946eae038e80617670eb11bf893fa04. По хорошему экстеншн бы переписать на трейты, в планах это есть, вот тогда думаю и будет лучше его переназвать
